version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - "9999:80"
    links:
      - php
    volumes:
      - ./logs/:/var/log/nginx

  php:
    build: ./php
    volumes:
      - ./php/:/var/www/html/

